name: Arduino IDE Library CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: esp32
            test: publish_and_subscribe
            core: "esp32:esp32@3.0.2"
            fqbn: "esp32:esp32:esp32"
            additional_libraries: []
          - name: samd
            test: publish_and_subscribe_mkr
            core: "arduino:samd"
            fqbn: "arduino:samd:mkrwifi1010"
            additional_libraries: ["WiFi101"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.target.core }}
          arduino-cli lib install MQTT@2.5.1
          if [ -n "${{ matrix.target.additional_libraries }}" ]; then
            for lib in ${{ matrix.target.additional_libraries }}; do
              arduino-cli lib install "$lib"
            done
          fi

      - name: Install repo as library
        run: |
          mkdir -p "$HOME/Arduino/libraries"
          ln -s "$PWD" "$HOME/Arduino/libraries/."

      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.target.fqbn }} examples/arduino/legacy_stack/${{ matrix.target.test }}
